<?php

/** template de rendu de GotHeader **/

$cssS = $this->scripts['css'];
$jsS = $this->scripts['js'];
$fonts = $this->scripts['font'];

foreach ($cssS as $css) {
    if (!str_starts_with($css, 'http://')) { ?>
        <link href="<?= $this->basePath($css) ?>" rel="stylesheet" type="text/css">
    <?php } else { ?>
        <link href="<?= $css ?>" rel="stylesheet" type="text/css">
    <?php }
}
foreach ($jsS as $js) {
    if (!str_starts_with($js, 'http://')) { ?>
        <script type="text/javascript" src="<?= $this->basePath($js) ?>"></script>
    <?php } else { ?>
        <script type="text/javascript" src="<?= $js ?>"></script>
    <?php }
}

if (!empty($fonts)) { ?>
    <style>
        <?php foreach ($fonts as $name => $fontURL) {
            $name = str_split('.', $name); ?>
        @font-face {
            font-family: '<?=$name?>';
            src: url('<?=$this->basePath($fontURL)?>') format("truetype");
        }

        <?php  } ?>
    </style>
<?php } ?>
