<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css")
        ->prependStylesheet($this->basePath('graphicobjecttemplating/css/got-main.css'))
        ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css")
        ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css")
        ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css")
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile("https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js")
    ?>
</head>
<body class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div id="gotcallback" style="display: none;">
    <?= $this->url("gotDispatch", array(), array('force_canonical' => true)) ?>
</div>
<div id="divwork" style="display: none"></div>
<div id="dpi"></div>

<nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; <?= date('Y') ?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
        </p>
    </footer>
</div>

<?= $this->inlineScript()
    ->prependFile("https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js")
    ->prependFile($this->basePath('graphicobjecttemplating/js/got-main.js'))
?>

<script>
    $(document).ready(function () {
        $(".gotObject").each(function () {
            let btClass = buildBootstrapClasses($(this).data("widthbt"));
            $(this).addClass(btClass);
            $(this).removeClass('hidden');
            $(this).addClass("display-" + $(this).data('display'));
        });
    });
</script>
</body>
</html>
