<?php
/** template de l'objet OSForm **/

$id = $this->objet['id'];
$classes = $this->objet['classes'];
$display = $this->objet['display'];
$object = $this->objet['object'];
$widthBT = $this->objet['widthBT'];
$codeCss = $this->objet['codeCss'];
$autoCenter = $this->objet['autoCenter'];
$acPx = $this->objet['acPx'];
$acPy = $this->objet['acPy'];
$content = $this->content;
$title = $this->objet['title'];
$widthBTbody = $this->objet['widthBTbody'];
$widthBTctrls = $this->objet['widthBTctrls'];
$btnsControls = $this->objet['btnsControls'];
$required = $this->objet['required'];
$submitEnter = $this->objet['submitEnter'];

$objClasses = 'gotObject hidden ' . $classes;

?>

<div id="<?=$id?>" class="<?=$objClasses?>" data-display="<?=$display?>" data-objet="<?=$object?>"
    <?php if ($widthBT) {?> data-widthbt="<?=$widthBT?>"<?php } ?>
>
    <style>
        <?php if ($codeCss){
        require_once __DIR__."/../../../../graphicobjecttemplating/oobjects/oscontainer/style.phtml";
        setCodeCss($codeCss);
        } ?>

        <?php if ($autoCenter){
        require_once __DIR__."/../../../../graphicobjecttemplating/oobjects/macros/autoCenter.phtml";
        setAutoCenter($id, $acPx, $acPy);
        } ?>
    </style>

    <?php if (!empty($title)) { ?>
    <h2 id="formTitle"><?=$title?></h2>
    <?php } ?>

    <?php
    $btnsCtrls = null;
    $dataWidthBTbody = 'datat-widthbt="'.$widthBTbody.'" ';
    $dataWidthBTctrls = 'datat-widthbt="'.$widthBTctrls.'" ';
    ?>

    <div class="gotObject formBody row" <?=$dataWidthBTbody?> data-display="<?=$display?>">
        <?=$content?>
    </div>

    <?php if (is_string($btnsControls) && strlen($btnsControls)) { ?>
    <div class="gotObject formCtrls form-group row " <?=$dataWidthBTctrls?> data-display="<?=$display?>">
        <?=$btnsControls?>
    </div>
    <?php } ?>

    <span class="error hidden"></span>
    <?php

    /** ###########################################################################################################
        ATTENTION : tout champ permettant une saisie d'information devra avoir une balise HTML label
        ceci pour permettre la mise en place de l'étoile rouge à gauche du texte inclus pour indiquer l'ensemble
        des champs obligatoires pour valider la saisie du formulaire
    ########################################################################################################### **/
    ?>
    <script id="<?=$id?>Script">
        function resetFormDatas(form) {
            $("#" + form).find(".gotObject").each(function () {
                if (!$(this).hasClass('formBody') && !$(this).hasClass('formCtrls') && this.dataset['objet'] !== 'odbutton') {
                    var valeur = this.dataset['default'];
                    switch (this.dataset['objet']) {
                        case 'odinput':
                            if (valeur === 'none') {
                                valeur = '';
                            }
                            $(this).find('input').val(valeur);
                            break;
                    }
                }
            })
        }

        <?php if ($required) { ?>
        function <?=$id?>Script() {
            var require = '<span style="color:red;float:left;width:10px;";>*&nbsp;</span>';
            var topRequire = false;
            <?php foreach ($required as $ident => $bool) {
                if ($bool) { ?>
            $("#<?=$ident?>").addClass('require');
            var mark = $("#<?=$ident?> label span");
            if (mark != undefined && mark.length == 0) {
                $("#<?=$ident?> label:first").html(require + $("#<?=$ident?> label:first").html());
            }
            if (!topRequire) { topRequire = true; }
           <?php }
            }?>

            if (topRequire) {
                var mention = $('span.require.mention');
                if (mention.length == 0) {
                    $("#<?=$id?>").append('<span class="require mention col-xs-12" style="font-weight: bold;"><span style="color:red;float:left;width: 10px;";>*&nbsp;</span> : champ(s) obligatoire(s)</span>');
                }
            }

            <?php if ($submitEnter) { ?>
            var submitBtn = $('#<?=$id?> div[data-objet="odbutton"][data-default="true"]');
            var objBuilder = submitBtn.data("objet");

            // gestion pression touche, si enter = soumission formulaire si existe
            $("#<?=$id?> .gotObject").on("keypress", function (e) {
                if (e.keyCode === 13) {
                    var submit<?=$id?> = eval('new ' + objBuilder + '($("#' + submitBtn.attr('id') + '"));');
                    invokeAjax(submit<?=$id?>.getData('click'), submitBtn.attr('id'), 'click', e);
                }
            });
            <?php } ?>
        }

        $(document).ready(function () {
            <?=$id?>Script();
        });
        <?php } ?>
    </script>
</div>