<?php

use GraphicObjectTemplating\OObjects\ODContained\ODTable;

$id = $this->objet['id'];
$object = $this->objet['object'];
$display = $this->objet['display'];
$widthBT = $this->objet['widthBT'];
$classes = $this->objet['classes'];
$cols = $this->objet['colsHead'];
$datas = $this->objet['datas'];
$events = $this->objet['events'];
$event = $this->objet['event'];
$styles = $this->objet['styles'];
$title = $this->objet['title'];
$titlePos = $this->objet['titlePos'];
$titleStyle = $this->objet['titleStyle'];

$objClasses = 'gotObject hidden ' . $id . " " . $classes;

require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/formatWidthBT.phtml";

function formatEvents(array $evtsTabs, string $id, string $object)
{
    $formatedEvents = [];
    foreach ($evtsTabs as $evt => $evtTab) {
        $corpsEvent =
            'let objetDOM = $(this);
             let objet = new ' . $object . '(objetDOM);
             var invalid = "";
             if (typeof objet.invalidate === "function") {
                invalid = objet.invalidate();
             }
             if (invalid.length == 0) {
                 $(this).remove("has-error");
                 $(this).find("span.error").removeClass("hidden").addClass("hidden");
                 invokeAjax(objet.getData("' . $evt . '"), "' . $id . '", "' . $evt . '", e);
             } else {
                 $(this).remove("has-error").addClass("has-error");
                 $(this).find("span.error").removeClass("hidden");
                 $(this).find("span.error").html(invalid);
             }';
        foreach ($evtTab as $noLine => $params) {
            foreach ($params as $noCol => $item) {
                $formatedSelector = "#" . $id . (((int)$noLine > 0) ? ' lno' . (int)$noLine : '') . (((int)$noCol > 0) ? ' cno' . (int)$noCol : '');
                $formatedEvents[] = $formatedSelector . "on('" . $evt . "', function(e) {" . $corpsEvent . "};";
            }
        }
    }
    return $formatedEvents;
}

function formatStyles(array $stylesTab, string $id) {
    $formatedStyles = [];
    foreach ($stylesTab as $noLine => $params) {
        foreach ($params as $noCol => $item) {
            $formatedSelector = "#" . $id . (((int)$noLine > 0) ? ' lno' . (int)$noLine : '') . (((int)$noCol > 0) ? ' cno' . (int)$noCol : '');
            $formatedStyles[] = $formatedSelector . " {" .$item. " }";
        }
    }
    return $formatedStyles;
}

?>

<div id="<?= $id ?>" class="<?=$objClasses?>" data-objet="<?= $object ?>" data-display="<?= $display ?>"
     data-widthbt="<?= $widthBT ?>"
    <?php if ($event) {
        require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/eventsHTML.phtml";
        setEvents($event);
    } ?>
>
    <style>
        #<?=$id?>_table {
            width: 100% !important;
        }

        <?php if (count($styles) > 0) {
            foreach (formatStyles($styles, $id) as $formatStyle) {
                echo $formatStyle;
            }
        } ?>

        div#<?=$id?> table tr td,
        div#<?=$id?> table tr th {
            padding: 0.2em;
        }

        <?php $loop = 0 ?>
        <?php $is_widthBT = false ?>
        <?php foreach($cols as $col) {
            $is_widthBT = $is_widthBT || array_key_exists('widthBT', $col);
            if (array_key_exists('width', $col) && !array_key_exists('widthBT', $col)) {
                $loop += 1; ?>
        div#<?=$id?> table .cno<?=$loop?> { width: <?=$col['width']?> }
            <?php } ?>
        <?php }
        if ($loop === 0 && !$is_widthBT) { ?>
        div#<?=$id?> table .col { width: <?=100/count($cols)?>%}
        <?php } ?>

        td .BAright {
            float: right;
            position: relative;
            margin-left: 0.5em;
        }

        td .BAleft {
            float: left;
            position: relative;
            margin-left: 0.5em;
        }

        .ico-custom:before {
            top: 0 !important;
            left: 0 !important;
        }

        .table-bordered td, .table-bordered th { border-color: #c7c0c0; }

        table caption {
            text-decoration: #666666;
            font-style: italic;
        <?php
        if (!empty($title) && !empty($titlePos)) {
            switch ($titlePos) {
                case ODTable::TABLETITLEPOS_BOTTOM_CENTER:
                    echo "caption-side: bottom;";
                    echo "text-align: center;";
                    break;
                case ODTable::TABLETITLEPOS_BOTTOM_LEFT:
                    echo "caption-side: bottom;";
                    echo "text-align: left;";
                    break;
                case ODTable::TABLETITLEPOS_BOTTOM_RIGHT:
                    echo "caption-side: bottom;";
                    echo "text-align: right;";
                    break;
                case ODTable::TABLETITLEPOS_TOP_CENTER:
                    echo "caption-side: top;";
                    echo "text-align: center;";
                    break;
                case ODTable::TABLETITLEPOS_TOP_LEFT:
                    echo "caption-side: top;";
                    echo "text-align: left;";
                    break;
                case ODTable::TABLETITLEPOS_TOP_RIGHT:
                    echo "caption-side: top;";
                    echo "text-align: right;";
                    break;
            }
        }
        if (!empty($titleStyle)) {
            echo $titleStyle;
        }
        ?>
        }
    </style>
    <table id="<?= $id ?>_table" class="lno0 cno0 table-bordered" data-lno="0" data-cno="0">
        <?php if (!empty($title)) {?>
        <caption><?=$title?></caption>
        <?php } ?>
        <thead class="<?= $id ?>Head">
        <tr class="line d-flex">
            <?php $loop = 0;
            foreach ($cols as $col) {
                $LwidthBT = array_key_exists('widthBT', $col) ? $col['widthBT'] : '';
                $Lwidth = array_key_exists('width', $col) ? $col['width'] : '';
                if ($col['view'] === true) {
                    $loop += 1;
                    $classTd = "col cno".$loop;
                    $styleTD = "";
                    if (!empty($LwidthBT) && empty($Lwidth)) {
                        $classTd .= ' '.formatWidthBT($LwidthBT);
                    } elseif (!empty($Lwidth) && empty($LwidthBT)) {
                        $styleTd = 'width: '.$Lwidth;
                    }
                    $libel = trim($col['libel']) ?>
                    <th class="<?=$classTd?>" data-col="<?=$loop?>"
                        <?php if (!empty($styleTd)) {?>style="<?=$styleTD?>"<?php } ?> >
                        <?= $libel ?>
                    </th>
                <?php } ?>
            <?php } ?>
        </tr>
        </thead>
        <tbody class="<?= $id ?>">
        <tr class="line nodata d-flex <?php if (count($datas) > 0) { ?>hide<?php } ?>">
            <?php $colspan = count($cols); ?>
            <td colspan="<?= $colspan ?>" class="<?=formatWidthBT(12)?>" style="text-align: center">No data to show</td>
        </tr>
        <?php if (count($datas) > 0) {
            foreach ($datas as $lno => $data) {
                if ($datas['view'] === true) {
                    $key = 'line' . $lno;
                    $data0 = $data[0]; ?>
                    <tr class="line d-flex lno<?= $lno ?>" data-lno="<?= $lno ?>">
                        <?php foreach ($data as $cno => $col) {
                            if ($cno > 0) {
                                if ($cols[$cno]['view'] === true) {
                                    $col = trim($col);
                                    $key = 'col' . $cno; ?>
                                    <td class="col cno<?= $cno ?>" data-cno="<?= $cno ?>"><?= $col ?></td>
                                <?php }
                            }
                        } ?>
                    </tr>
                <?php } ?>
            <?php } ?>
        <?php } ?>
        </tbody>
    </table>

    <script id="<?= $id ?>Script">
        <?php if (!empty($events)) {
            foreach (formatEvents($events, $id, $object) as $formatEvent) {
                echo $formatEvent;
            }
        } ?>

        <?php if (!empty($event)) { ?>
        $(document).ready(function (e) { <?php
            require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/eventsJS.phtml";
            setOnEvents($event, $this->objet);
            ?> });
        <?php } ?>
    </script>
</div>