<?php
require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/macros/formatWidthBT.phtml";

$id = $this->objet['id'];
$object = $this->objet['object'];
$display = $this->objet['display'];
$widthBT = $this->objet['widthBT'];
$classes = $this->objet['classes'];
$cols = $this->objet['colsHead'];
$datas = $this->objet['datas'];
$events = $this->objet['events'];
$event = $this->objet['event'];
$styles = $this->objet['styles'];

// traitement récupération largeurs de colonnes et absence de définition de largeurs de colonnes
$colsWidth = array_key_exists('colsWidth', $this->objet) ? $this->objet['colsWidth'] : [];
$colsWidthBT = array_key_exists('colsWidthBT', $this->objet) ? $this->objet['colsWidth'] : [];
if (empty($colsWidth) && empty($colsWidthBT)) {
    $width = 12 / count($cols);
    $sum_width = 0;
    for ($ind = 0, $indMax = count($cols); $ind < $indMax; $ind++) {
        if ($ind == ($indMax - 1) and is_float($width)) {
            $width = 12 - $sum_width;
        }
        $colsWidthBT[$ind] = (int)$width;
        $sum_width += (int)$width;
    }
}

$objClasses = 'gotObject hidden ' . $id . " " . $classes;

require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/macros/formatWidthBT.phtml";

function formatEvents(array $evtsTabs, string $id, string $object)
{
    $formatedEvents = [];
    foreach ($evtsTabs as $evt => $evtTab) {
        $corpsEvent =
            'let objetDOM = $(this);
             let objet = new ' . $object . '(objetDOM);
             var invalid = "";
             if (typeof objet.invalidate === "function") {
                invalid = objet.invalidate();
             }
             if (invalid.length == 0) {
                 $(this).remove("has-error");
                 $(this).find("span.error").removeClass("hidden").addClass("hidden");
                 invokeAjax(objet.getData("' . $evt . '"), "' . $id . '", "' . $evt . '", e);
             } else {
                 $(this).remove("has-error").addClass("has-error");
                 $(this).find("span.error").removeClass("hidden");
                 $(this).find("span.error").html(invalid);
             }';
        foreach ($evtTab as $noLine => $params) {
            foreach ($params as $noCol => $item) {
                $formatedSelector = "#" . $id . (((int)$noLine > 0) ? ' lno' . (int)$noLine : '') . (((int)$noCol > 0) ? ' cno' . (int)$noCol : '');
                $formatedEvents[] = $formatedSelector . "on('" . $evt . "', function(e) {" . $corpsEvent . "};";
            }
        }
    }
    return $formatedEvents;
}

function formatStyles(array $stylesTab, string $id)
{
    $formatedStyles = [];
    foreach ($stylesTab as $noLine => $params) {
        foreach ($params as $noCol => $item) {
            $formatedSelector = "#" . $id . (((int)$noLine > 0) ? ' lno' . (int)$noLine : '') . (((int)$noCol > 0) ? ' cno' . (int)$noCol : '');
            $formatedStyles[] = $formatedSelector . " {" . $item . " }";
        }
    }
    return $formatedStyles;
}

?>

<div id="<?= $id ?>" class="<?= $objClasses ?>" data-objet="<?= $object ?>" data-display="<?= $display ?>"
     data-widthbt="<?= $widthBT ?>"
    <?php if ($event) {
        require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/macros/eventsHTML.phtml";
        setEvents($event);
    } ?>
>
    <style>

        <?php if (empty($colsWidthBT)) {
            $loop = -1;
            foreach ($colsWidth as $width) {
                $loop++;
                echo '.col'+$loop+' { width: '+$width+' !important; }';
            }
        }?>
    </style>

    <div id="<?= $id ?>_table" class="<?= $objClasses ?> lno0 cno0 table" data-lno="0" data-cno="0"
         data-display="<?= $display ?>" data-widthbt="<?= $widthBT ?>">
        <div class="<?= $id ?>Head thead">
            <div class="line row">
                <?php foreach ($cols as $col) {
                    $loop = -1;
                    if ($col['view'] === true) {
                        $loop += 1;
                        $classTd = "col cno" . $loop . ' ';
                        if (empty($colsWidthBT)) {
                            $classTd += ' col' + $loop;
                        } else {
                            $classTd .= formatWidthBTstr($colsWidthBT[$loop]);
                        }
                        $styleTD = "";
                        $libel = trim($col['libel']) ?>
                        <div class="<?= $classTd ?> th" data-col="<?= $loop ?>" scope="col"
                            <?php if (!empty($styleTd)) { ?> style="<?= $styleTD ?>"
                            <?php } ?> >
                            <?= $libel ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
        <div class="<?= $id ?>TBody tbody">
            <div class="line row nodata <?php if (count($datas) > 0) { ?>hide<?php } ?>">
                <div style="text-align: center" class="<?= formatWidthBTstr(12) ?> td">
                    <span>No data to show</span>
                </div>
            </div>
            <?php if (count($datas) > 0) {
                foreach ($datas as $lno => $data) {
                    if ($datas['view'] === true) {
                        $key = 'line' . $lno;
                        $data0 = $data[0]; ?>
                        <div class="tr line lno<?= $lno ?>" data-lno="<?= $lno ?>">
                            <?php foreach ($data as $cno => $col) {
                                if ($cno > 0) {
                                    if ($cols[$cno]['view'] === true) {
                                        $col = trim($col);
                                        $key = 'col' . $cno; ?>
                                        <div class="td col cno<?= $cno ?>" data-cno="<?= $cno ?>"><?= $col ?></div>
                                    <?php }
                                }
                            } ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </div>
    </div>

    <script id="<?= $id ?>Script">
        <?php if (!empty($events)) {
            foreach (formatEvents($events, $id, $object) as $formatEvent) {
                echo $formatEvent;
            }
        } ?>

        <?php if (!empty($event)) { ?>
        $(document).ready(function (e) { <?php
            require_once __DIR__ . "/../../../../graphicobjecttemplating/oobjects/macros/eventsJS.phtml";
            setOnEvents($event, $this->objet);
            ?> });
        <?php } ?>
    </script>
</div>