<?php
/** template pour l'ajout de la gestion des évènements à tout objet
 * l'event 'dummy' permet de programmer manuellement un évènement JavaScript sans déclenchement de callback
 **/
function setOnEvents($events, $objet, $tag = null)
{
    $str = '';
    foreach ($events as $evt => $event) {
        if (!empty($event)) {
            if ($event['class'] !== 'dummy') {
                $str .= '$(".' . $objet['id'] . '").on("' . $evt . '", ';
                if ($tag) { $str .= '"' . $tag . '",'; }
                $str .= " function (e) {";
                if ($event['class'] === "javascript:") {
                    $str .= $event['method'];
                } else {
                    $str .= 'let objetDOM = $(this);';
                    $str .= 'let objet = new ' . $objet['object'] . '(objetDOM);';
                    $str .= 'var invalid = "";';
                    $str .= 'if (typeof objet.invalidate === "function") {';
                    $str .= 'invalid = objet.invalidate();';
                    $str .= '}';
                    $str .= 'if (invalid.length == 0) {';
                    $str .= '    $(this).remove("has-error");';
                    $str .= '    $(this).find("span.error").removeClass("hidden").addClass("hidden");';
                    $str .= '    invokeAjax(objet.getData("' . $evt . '"), "' . $objet['id'] . '", "' . $evt . '", e);';
                    $str .= '} else {';
                    $str .= '    $(this).remove("has-error").addClass("has-error");';
                    $str .= '    $(this).find("span.error").removeClass("hidden");';
                    $str .= '    $(this).find("span.error").html(invalid);';
                    $str .= '}';
                }
                $str .= "});";
            }
        }
    }
    return $str;
}