<?php

function setAutoCenter($id, $acPx, $acPy) {
    echo "#<?=$id?> { ";
    echo "    width: <?=$acPx?>; ";
    echo "    height:  <?=acPy?>; ";
    echo "    position: absolute; ";
    echo "    top:0; ";
    echo "    bottom: 0; ";
    echo "    left: 0; ";
    echo "    right: 0; ";
    echo "    margin: auto; ";
    echo "    padding: 15px !important; ";
    echo "    border: 1px solid black; ";
    echo "    background-color: white; ";
    echo "} ";
}